[package]
name = "rust_key_box"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rsa = { version = "0.8.2", features = ["std", "pem", "pkcs5"] }
scanpw = "0.1.0"
