[package]
name = "rust_key_box"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magic-crypt = "3.1.12"
rand = "0.8.5"
rsa = "0.8.2"
scanpw = "0.1.0"
